
```{r}
library(tidyverse)
library(dplyr)

questions <- read_csv("questions.csv")
answer <- read_csv("answers.csv")
tags <- read_csv("tags.csv")
question_tags <- read_csv("question_tags.csv")
```
#1. Left-joing questions and tags

```{r}

#INCISO 1.1
questions%>%
  left_join(question_tags, by = c("id"= "question_id") )

#INCISO 1.2
questions%>%
  left_join(question_tags, by = c("id"= "question_id") ) %>%
  left_join(tags, by = c("tag_id"="id"))

#INCISO 1.3
questions%>%
  left_join(question_tags, by = c("id"= "question_id") ) %>%
  left_join(tags, by = c("tag_id"="id")) %>%
  mutate(tag_name = replace_na(tag_name, "only-r"))

#INCISO 1.4
questions_with_tags <- questions%>%
  left_join(question_tags, by = c("id"= "question_id") ) %>%
  left_join(tags, by = c("tag_id"="id")) %>%
  mutate(tag_name = replace_na(tag_name, "only-r"))

questions_with_tags


```
#2. comparing scores across tags
```{r}
#INCISO 2.1
questions_with_tags %>%
  group_by(tag_name)

#inciso 2.2
questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score = mean(score))

#inciso 2.3
questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score = mean(score)) %>%
  arrange(desc(mean_score))
```
#3. finding gaps between questions and answers
```{r}
#inciso 3.1
questions
answer
questions %>%
  inner_join(answer, by =c("id"= "question_id"), suffix = c("_question", "_answer"))

#inciso 3.2
questions %>%
  inner_join(answer, by =c("id"= "question_id"), suffix = c("_question", "_answer"))%>%
  mutate(gap = creation_date_answer - creation_date_question)

```
#.4 joining question and answer counts
```{r}
#inciso 4.1
answer_counts <- answer %>%
  count(question_id) %>%
  arrange(question_id)
answer_counts

#inciso 4.2
questions %>%
  left_join(answer_counts, by =c("id"= "question_id"))

#inciso 4.3
questions %>%
  left_join(answer_counts, by =c("id"= "question_id"))%>%
  mutate(n = replace_na(n,0))

#inciso 4.4
 question_answer_counts <-  questions %>%
  left_join(answer_counts, by =c("id"= "question_id"))%>%
  mutate(n = replace_na(n,0))
 question_answer_counts
 
```

