
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
dinamonds <- read_csv('diamonds.csv')
glimpse(dinamonds)  #que tipo de de datos se estan leyendo
dinamonds
```
inciso 1 Dispersion

```{r}
# 1.1
dispersion_1 <- ggplot(dinamonds, aes(x = carat, y = price))+
  geom_point()
dispersion_1

#1.2
dispersion_2 <- ggplot(dinamonds, aes(x = carat, y = price, color = clarity))+
  geom_point()+
  scale_y_log10()

#1.3
dispersion_2



```
HISTOGRAMA

```{r}
#2.1

histograma <- ggplot(dinamonds, aes(x = price))+
  geom_histogram(bins = 40)
histograma

#2.2
histograma_2 <- ggplot(dinamonds, aes(x = price))+
  geom_histogram(bins = 40) +
  scale_x_log10() +
  scale_y_log10()
histograma_2


histograma
histograma_2


```
BOXPLOTS
```{r}
#3.1
ggplot(dinamonds, aes(x=cut, y= price))+
  geom_boxplot() +
  scale_y_log10()

#3.2
ggplot(dinamonds, aes(x=cut, y= price, fill = cut))+
  geom_boxplot() +
  scale_y_log10()
```
FACETING
```{r}
#4.1
filtered_price <- dinamonds %>%
  filter(price > 1000 & cut %in% c("Good","Ideal","Premium"))
filtered_price


#4.2

ggplot(filtered_price, aes(x= cut, y= depth))+
  geom_bar(stat = "identity")

#4.3
ggplot(filtered_price, aes(x= cut, y= depth))+
  geom_bar(stat = "identity") +
  facet_wrap(~ clarity)

#4.4
ggplot(filtered_price, aes(x= cut, y= depth, fill = clarity))+
  geom_bar(stat = "identity") +
  facet_wrap(~ clarity)
```
GROUPING AND SUMMARIZING
```{r}
#1
median_dimension_diamond <- dinamonds %>%
  group_by(cut) %>%
  summarize(mediaX = mean(x), mediaY = mean(y), mediaZ = mean(z))

median_dimension_diamond
  
#2

cut_premium <- diamonds %>%
  filter(cut == "Premium") %>%
  group_by(clarity) %>%
  summarize(minPrice = min(price), maxPrice = max(price))
cut_premium

#3

ggplot(cut_premium, aes(x= clarity, y= maxPrice, fill = clarity)) +
  geom_bar(stat = "identity")

```


